import {
  Stethoscope, SmilePlus, Sparkles, Ribbon, HeartPulse,
} from "lucide-react";

export const treatments = [
  {
    slug: "prp-hair",
    label: "PRP/GFC for Hair",
    fullTitle: "PRP/GFC for Hair",
    icon: Sparkles,
    color: "#0E898F",
    bgColor: "#E6F4F4",
    image: "/images/treatment-dermatology.png",
    heroDesc: "Natural hair regrowth therapy using your own platelet-rich plasma for stronger, healthier hair growth.",
    features: [
      "Natural regrowth",
      "No side effects",
      "Strengthens follicles",
      "Minimally invasive",
      "Clinically proven",
      "Quick recovery",
    ],
    description: "PRP (Platelet-Rich Plasma) and GFC (Growth Factor Concentrate) are advanced, non-surgical treatments for hair loss. By using your own blood's growth factors, we stimulate hair follicles to promote natural regrowth and improve hair density.",
    stats: { doctors: 10, patients: "2K+", experience: "8 years" },
  },
  {
    slug: "general-opd",
    label: "General OPD",
    fullTitle: "Your First Step to Better Health Starts Here",
    icon: Stethoscope,
    color: "#0E898F",
    bgColor: "#E6F4F4",
    image: "/images/treatment-opd.png",
    heroDesc: "Get quick and reliable consultations for everyday health concerns. Our experienced doctors ensure accurate diagnosis and the right treatment — without long waiting times.",
    features: [
      "Walk-in & appointment-based consultations",
      "Comprehensive health screening",
      "Referral to specialists when needed",
      "Health certificates & fitness assessments",
      "Chronic disease management",
      "Vaccination & immunization services",
    ],
    description: "The General OPD at MediCare+ is your first point of contact for any health concern. Our experienced general physicians conduct thorough examinations, prescribe treatments, and refer you to specialists when necessary. We believe that accessible primary care is the foundation of good health.",
    stats: { doctors: 45, patients: "12K+", experience: "16 years" },
  },
  {
    slug: "dental",
    label: "Dental",
    fullTitle: "Confident Smiles Begin with Expert Dental Care",
    icon: SmilePlus,
    color: "#10B981",
    bgColor: "#D1FAE5",
    image: "/images/treatment-dental.png",
    heroDesc: "From routine checkups to advanced dental treatments, we provide painless, modern, and affordable solutions to keep your smile healthy and bright.",
    features: [
      "Teeth cleaning & polishing",
      "Root canal treatment",
      "Dental implants & crowns",
      "Orthodontics & braces",
      "Teeth whitening",
      "Wisdom tooth extraction",
    ],
    description: "Our dental department combines modern technology with expert care to give you a healthy, confident smile. From routine check-ups to advanced cosmetic procedures, our team of dental specialists ensures a comfortable experience with outstanding results.",
    stats: { doctors: 20, patients: "8K+", experience: "12 years" },
  },
  {
    slug: "dermatology",
    label: "Dermatology",
    fullTitle: "Healthy Skin, Confident You",
    icon: Sparkles,
    color: "#EC4899",
    bgColor: "#FCE7F3",
    image: "/images/treatment-dermatology.png",
    heroDesc: "Treat acne, pigmentation, hair issues, and more with expert dermatologists. Personalized care for glowing, clear, and healthy skin.",
    features: [
      "Acne & scar treatment",
      "Laser therapy & skin resurfacing",
      "Hair loss treatment (PRP)",
      "Mole & skin tag removal",
      "Psoriasis & eczema management",
      "Anti-aging & cosmetic procedures",
    ],
    description: "Our dermatology department addresses a wide range of skin conditions using the latest diagnostic tools and treatments. Whether it's medical dermatology or cosmetic enhancements, our board-certified dermatologists deliver personalized, evidence-based care.",
    stats: { doctors: 15, patients: "6K+", experience: "10 years" },
  },
  {
    slug: "cancer",
    label: "Cancer",
    fullTitle: "Compassionate Care. Advanced Cancer Treatment.",
    icon: Ribbon,
    color: "#8B5CF6",
    bgColor: "#EDE9FE",
    image: "/images/treatment-cancer.png",
    heroDesc: "Early detection, expert oncologists, and personalized treatment plans — supporting you at every stage with care, strength, and hope.",
    features: [
      "Early cancer screening & detection",
      "Chemotherapy & immunotherapy",
      "Radiation therapy",
      "Surgical oncology",
      "Palliative & supportive care",
      "Genetic counseling & testing",
    ],
    description: "Our oncology center brings together a multidisciplinary team of cancer specialists to provide comprehensive treatment plans tailored to each patient. We combine the latest research, advanced technology, and compassionate care to fight cancer at every stage.",
    stats: { doctors: 30, patients: "5K+", experience: "14 years" },
  },
  {
    slug: "cardiology",
    label: "Cardiology",
    fullTitle: "Cardiology & Heart Care",
    icon: HeartPulse,
    color: "#EF4444",
    bgColor: "#FEE2E2",
    image: "/images/treatment-cardiology.png",
    heroDesc: "State-of-the-art cardiac diagnostics, interventions, and preventive care. Our cardiologists are leaders in treating complex cardiovascular conditions.",
    features: [
      "ECG, Echo & stress testing",
      "Cardiac catheterization & angioplasty",
      "Heart failure management",
      "Pacemaker & defibrillator implants",
      "Preventive cardiology programs",
      "Cardiac rehabilitation",
    ],
    description: "Our cardiology department is equipped with the most advanced diagnostic and interventional tools. From preventive heart health programs to complex cardiac surgeries, our experienced cardiologists are dedicated to keeping your heart strong and healthy.",
    stats: { doctors: 25, patients: "10K+", experience: "18 years" },
  },
];
